### ISSUE TITLE
Quickly starting the same assistant makes Daily throw and Vapi not send any event

### ISSUE THREAD

**Issue by stanlrt** [VapiAI/client-sdk-web#70]
If you quickly start the same assistant (e.g. quickly reloading the page), Vapi will sometimes (couldn't isolate a specific situation) bubble up the following error from the Daily lib:

"Duplicate DailyIframe instances are not allowed"

The strange thing is that the assistant starts fine. However, Vapi will not send any events (eg. speech-start) to the client, which is problematic.

---

In the meantime our workaround is just to catch the specific error and reload the page

**Comment by nikhilro** [comment]
add a log before `vapi.start`. due to some react re-render or sth, it's likely getting called multiple times

**Comment by stanlrt** [comment]
That's correct, we called `stop` before calling `start` in that case but apparently that wasn't the right solution
