### ISSUE TITLE
How to make audio play as media, not phone, on Android

### ISSUE THREAD

**Issue by stanlrt** [VapiAI/client-sdk-web#76]
Hello,

We are using Vapi for a conversational app. Sadly the audio is playing through the phone channel on Android. For some reason, the maximum volume is much lower than the one of the media channel. It also uses hands-free mode for headphones.

Is there a way to make Vapi use the media channel? I tried using `setSinkId` on the `audio` element but it's not supported on mobile browsers.

**Comment by nikhilro** [comment]
hey @stanlrt , does it work to get the underlying daily object: https://github.com/VapiAI/client-sdk-web/blob/ecfb47bbe3c91bde28abc65a0fb8974d4b72b55c/vapi.ts#L424 and then you can get whatever track you want

**Comment by stanlrt** [comment]
Thanks @nikhilro, that seems promising. The lower max volume+hands-free problem seemed to be an issue specific to the user's phone, so I'll just close the issue.
